# -*- coding: utf-8 -*-
"""Diabetes_Predict_Project_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cgXajx4KZgWCZnzwgH9jRfK5n8ITVyuJ
"""

# -------------------------------
# Import Libraries
# -------------------------------
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay

# -------------------------------
# Load Dataset
# -------------------------------
file_path = "C:\\Second Year Files L.R Assigments & Projects\\SEM 4 ML\\ML Project Diabetes Prediction\\Diabetes_Dataset_Project.xlsx"
df = pd.read_excel(file_path)

# Preview data
df.head()

# -------------------------------
# Clean and Shorten Column Names
# -------------------------------
df.columns = df.columns.str.strip()  # remove any leading/trailing spaces

# Mapping of long names → short names
short_names = {
    'age': 'Age',
    'Height_cm': 'Height',
    'Weight_kg': 'Weight',
    'bmi': 'BMI',
    'Gender': 'Gender',
    'How would you describe your daily diet?': 'Diet',
    'family_history': 'FamilyHist',
    'How often do you consume sugary foods or drinks?': 'SugarFreq',
    'How many days per week do you exercise or do physical activity?': 'ExerciseDays',
    'Do you experience frequent thirst or dry mouth?': 'Thirst',
    'Do you feel unusually tired most of the time?': 'Tired',
    'Do you urinate more frequently than usual?': 'Urination',
    'Do you have high blood pressure?': 'HighBP',
    'diabetes': 'Diabetes'
}

# Apply rename
df.rename(columns=short_names, inplace=True)

# Verify
print(df.columns)

df.head()

# -------------------------------
# Encode Categorical Columns
# -------------------------------
label_encoder = LabelEncoder()
for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = label_encoder.fit_transform(df[column])

# -------------------------------
# Split Features and Target
# -------------------------------
target_column = 'Diabetes'
X = df.drop(target_column, axis=1)
y = df[target_column]

# -------------------------------
# Train-Test Split
# -------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -------------------------------
# Feature Scaling
# -------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# -------------------------------
# Initialize Models
# -------------------------------
lr_model = LogisticRegression()
knn_model = KNeighborsClassifier()
dt_model = DecisionTreeClassifier(random_state=42)

models = {
    'Logistic Regression': lr_model,
    'KNN': knn_model,
    'Decision Tree': dt_model
}

# -------------------------------
# Train, Predict & Evaluate
# -------------------------------
results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    results[name] = {'Accuracy': acc, 'F1 Score': f1}

# Print Results
for name, metrics in results.items():
    print(f"{name}: Accuracy = {metrics['Accuracy']:.4f}, F1 Score = {metrics['F1 Score']:.4f}")

# -------------------------------
# Select Best Model
# -------------------------------
best_model_name = max(results, key=lambda x: results[x]['F1 Score'])
best_model = models[best_model_name]
print(f"\nBest Model: {best_model_name}")

plt.figure(figsize=(5,4))
df['Diabetes'].value_counts().plot(kind='bar', color=['skyblue', 'salmon'])
plt.xlabel("Diabetes Diagnosis")
plt.ylabel("Count")
plt.title("Diabetes Diagnosis Distribution")
plt.show()

# -------------------------------
# Confusion Matrix for Best Model
# -------------------------------
y_pred_best = best_model.predict(X_test)
cm = confusion_matrix(y_test, y_pred_best)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=best_model.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title(f"{best_model_name} Confusion Matrix")
plt.show()

# -------------------------------
# Accuracy Comparison Bar Chart
# -------------------------------
plt.figure(figsize=(6,4))
model_names = list(results.keys())
accuracies = [results[m]['Accuracy'] for m in model_names]
plt.bar(model_names, accuracies, color=['skyblue', 'lightgreen', 'salmon'])
plt.xlabel("Models")
plt.ylabel("Accuracy")
plt.title("Model Accuracy Comparison")
plt.show()

plt.figure(figsize=(6,4))
colors = df['Diabetes'].map({0:'skyblue', 1:'salmon'})  # blue = non-diabetic, red = diabetic
plt.scatter(df['BMI'], df['Diabetes'], c=colors, alpha=0.6)
plt.xlabel("BMI")
plt.ylabel("Diabetes")
plt.title("BMI vs Diabetes Diagnosis")
plt.show()

